dist: trusty
sudo: false
cache:
  yarn: true
language: node_js
env:
  global:
  - secure: o1E51adkfzse6ayaKkf+YPi4xMxDvj6ez1oEsI5HljhVuMbgvOYkrs3dkOSfsORBAR+a9F8bSbrOcXyBDzloj3v1G47r4LaSWFk8QTBDvn8cpAzbx1eErT6FcdzxqmeZ22xWXQhEg17mfomCvULc+ueDToXEP1GGkozp7KZyldk=
  - secure: AtH9KI7WHnPtxn+ib+BJTKSe7Rr7B3nzwxXEy+dPOhGTT+DikM1XnNOoDaebsx2a1h4JnLZ+6MafpLWmH30us4t3xcqju/Amymf8zhcKswPNnmAzuY+LYgULmpbJ9QHz2X+yh/5eTCe7EzIsSD3nj/XPYzRLQynp47uZnjG+F54=
addons:
  browserstack:
    username: dev@treasure-data.com
    access_key:
      secure: knd/zgP9vNnNj5AlYbHr4AK/B4A/V+FtQAGoE4IWnnD5VXf054LT4Nd0d7J23Zau77JjGDLwJmW2J+BZA/zCVmbyw0x0/JrFjPe7pdNGBWd4LLk8R/qqXl+3h6wJiN1IR6US0vBI+lUAFSnn7unfHd4i8/8suLVb1lpvSc0nP/E=
