dist: trusty
sudo: false
cache:
  yarn: true
language: node_js
env:
  global:
  - secure: C5yaHRgSicbQeM2RjnKD24f+JIJwqEOcGCGObgca8/oYrTEtEO2sbTVw/g23LknmcwPKulKfP9zZQ/+Skx3Yqx8d2cR5QjyktqaiNarjCGiG6RDGkvEzPebtSqyw5C7ZHv+zHVaWNXUmHSX/2Zy8rGEQwoCTNv21hjI5zTAUaWA=
  - secure: AtH9KI7WHnPtxn+ib+BJTKSe7Rr7B3nzwxXEy+dPOhGTT+DikM1XnNOoDaebsx2a1h4JnLZ+6MafpLWmH30us4t3xcqju/Amymf8zhcKswPNnmAzuY+LYgULmpbJ9QHz2X+yh/5eTCe7EzIsSD3nj/XPYzRLQynp47uZnjG+F54=
addons:
  browserstack:
    username: dev@treasure-data.com
    access_key:
      secure: knd/zgP9vNnNj5AlYbHr4AK/B4A/V+FtQAGoE4IWnnD5VXf054LT4Nd0d7J23Zau77JjGDLwJmW2J+BZA/zCVmbyw0x0/JrFjPe7pdNGBWd4LLk8R/qqXl+3h6wJiN1IR6US0vBI+lUAFSnn7unfHd4i8/8suLVb1lpvSc0nP/E=
