dist: trusty
sudo: false
cache:
  yarn: true
language: node_js
env:
  global:
  - secure: Eu9IdOCMDNNtwjs0901xE53zsl6ExoZnGTo+8kOEy4qtZj0/PVCHPEfx3Ty9QFm5mSLVW6BVkJB4gHjZPuSKbMYrKIXwSFZcML4xYXMs7oWh2e9ulOVf8iSH/5MPj8+ib+UPcdwkJLhHXm3lIZs+PhySkIFbA045uPXVRT2Xusw=
  - secure: XCtfTIWdmyjp1ZDH9CPs7eXbOTAhfS031GWsru7rlOqPTWy0/RHL3BI5chBnn7Dh6ig34M6jQ2/4hcP/Qy+nPR9Gx44GF0jhEv3oEF5fyeSu3DsanKew3K0CIbnNRC4lEr/4qMaDkN4yLFeYCYpuvr0v2pyGpP9e+k7j3oqOmM8=
  - secure: C5yaHRgSicbQeM2RjnKD24f+JIJwqEOcGCGObgca8/oYrTEtEO2sbTVw/g23LknmcwPKulKfP9zZQ/+Skx3Yqx8d2cR5QjyktqaiNarjCGiG6RDGkvEzPebtSqyw5C7ZHv+zHVaWNXUmHSX/2Zy8rGEQwoCTNv21hjI5zTAUaWA=
  - secure: VuUlF+SdWvjKA0jDLJWcHwaL+H/4shfLhy/1C3HulJVuAOtz7+UQvOsbo2s8tXQic25IynvnBxb366wbDHS4yPEi71oTH/KniV3rYa9jsDM/vIUsHi8X09Scwk8CyD84F7aEL3hKWnWlNFxgRN3YgjenRX9qeDGsG6fLin2i670=
addons:
  browserstack:
    username: dev@treasure-data.com
    access_key:
      secure: ZLJQWW+CCYayaI49i7bPqK/1HVFX4qSDKZMVBkkj8RiRdkQ86QBejP4+QW77JbVGbvctfJVLLdumsWhpZGMRbz4eVV6UMvJ4PsqGuXjoaWRGqo6Q6VgCQfZJlsnhAmjbq7b1VKLo837CWDRGCem8O0hX+/GwoN5aegQz3sfLDA0=
